### ISSUE TITLE
Problem / Frage 

### ISSUE THREAD

**Issue by M3ll0wHD** [BedwarsRel/BedwarsRel#403]
Wie kann man in den konfig Datein die Haltbarkeit von zB. Bögen oder Schwertern im shop anpassen

**Comment by HobbyzockerLP** [comment]
enchants:
ID:Level

Kannst du auch in der standart shop.yml abgucken...

**Comment by M3ll0wHD** [comment]
Sry für meine falsche Wortwahl ich meine mit Haltbarkeit nicht das enchantment sondern die durability also die maximalen uses bis der Gegenstand kaputt geht 

Danke für die schnelle Antwort 

mfg 
Justin Seiffert

**Comment by sebastianbinder** [comment]
Hi @M3ll0wHD 
Vielen Dank für deinen Vorschlag. Mal sehen wann und inwieweit das umsetzbar ist :)

**Comment by HobbyzockerLP** [comment]
Durability: xyz
Das gibt es doch oder?

**Comment by Block-Build** [comment]
@sebastianbinder ist das mit dem neuen Shop umsetzbar?

**Comment by sebastianbinder** [comment]
In der aktuellen Form so standardmäßig auch nicht.

**Comment by Block-Build** [comment]
@sebastianbinder es ist in der aktuellen Form umsetzbar :)
@M3ll0wHD hier 2 Beispiele:
```yml
    - reward:
      - type: BOW
        damage: 100
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Bogen I

    - reward:
      - type: LEATHER_HELMET
        damage: 50
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          display-name: Lederhelm
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
            DURABILITY: 1
```
Wie du wahrscheinlich bemerkt hast kann man die Haltbarkeit mit `damage: int` bearbeiten
