### ISSUE TITLE
Tränke kosten alle gleich

### ISSUE THREAD

**Issue by Boy132** [BedwarsRel/BedwarsRel#611]
Hab momentan diesen Shop, also diese Angebote im Tab:
http://pastebin.com/qsknsZbJ

Aber egal welchen Trank ich kaufe, ich bezahle immer 3 Eisenbarren. Hab auch schon andere Methoden, wie im Wiki steht, ausprobiert. Immer das Gleiche Problem.

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please have a look on https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.

**Comment by sebastianbinder** [comment]
Nevermind. Did some debugging. Potion support is pretty ugly because of those different minecraft versions. Update your shop as shown below and it should work. If not, please tell me and I'll do some more research.
```yml
    - reward:
      - type: POTION
        damage: 8197
        meta:
          ==: ItemMeta
          meta-type: POTION
          display-name: §rTrank der Heilung I
          custom-effects:
          - ==: PotionEffect
            effect: 6
            duration: 1
            amplifier: 0
            ambient: true
            has-particles: true
      price:
      - type: IRON_INGOT
        amount: 3
    - reward:
      - type: POTION
        damage: 8229
        meta:
          ==: ItemMeta
          meta-type: POTION
          display-name: §rTrank der Heilung II
          custom-effects:
          - ==: PotionEffect
            effect: 6
            duration: 1
            amplifier: 0
            ambient: true
            has-particles: true
      price:
      - type: IRON_INGOT
        amount: 5
    - reward:
      - type: POTION
        damage: 8194
        meta:
          ==: ItemMeta
          meta-type: POTION
          display-name: §rTrank der Schnelligkeit
          custom-effects:
          - ==: PotionEffect
            effect: 1
            duration: 3600
            amplifier: 0
            ambient: true
            has-particles: true
      price:
      - type: IRON_INGOT
        amount: 7
    - reward:
      - type: POTION
        damage: 8201
        meta:
          ==: ItemMeta
          meta-type: POTION
          display-name: "§rTrank der Stärke"
          custom-effects:
          - ==: PotionEffect
            effect: 5
            duration: 3600
            amplifier: 0
            ambient: true
            has-particles: true
      price:
      - type: GOLD_INGOT
        amount: 8
```
