### ISSUE TITLE
trank mit Effektstärke 255

### ISSUE THREAD

**Issue by CombatTiger** [BedwarsRel/BedwarsRel#649]
Ich habe bemerkt, dass unter der 1.8 die Tränke mit der neusten Version des Plugins und neu generierter Config.yml die Tränke nicht funktionieren. Dies war für mich nicht weiter schlimm, da ich für den Abschnitt der Tränke die Alte Struktur für Tränke eingefügt habe und es ging.
Ich wollte nun aber einen Trank mit maximaler Sprungkraft hinzufügen, da dieseer keine Sprungkraft mehr verleiht, sondern nur den Fallschaden verhindert. (/effect @p minecraft:jump_boost 255 255 [true] wäre die Entsprechung Ingame). Die maximale Zahl bei amplifier ist jedoch 127, ich gehe also davon aus, dass du mit zwei multiplizierst, da dies eben 254 ergibt. Leider verhindert dies eine Eingabe von 255, welches 127.5 enspräche. Eine Eingabe von dezimalzahlen scheint jedoch nicht vorgesehen.
Ich hoffe, dass ich das richtig als Fehler eingeordnet habe und nicht als request poste.

MfG

CombatTiger

**Comment by sebastianbinder** [comment]
@CombatTiger Schick doch bitte mal den Teil der Config mit dem Trank...

**Comment by CombatTiger** [comment]
Hier kannst du dir meine shop.yml im Browser anshehen: http://dl.oxygenmc.de/shop.yml
oder Ziel speichern unter wählen.
Ich habe den unteren Abschnitt der Shop.yml in den einer älteren Version verändert (Nur der Trankbereich). Der Letzte Trank der Liste soll (zumindest nach meinem Verständnis von Minecraft Vanilla) bei amplifier: 127 den Wert 255 erhalten, also den maximal Möglichen Effekt, der eben keine Sprungkraft mehr gibt, sondern den Fallschaden verhindert.

**Comment by sebastianbinder** [comment]
@CombatTiger 
> Der Letzte Trank der Liste soll (zumindest nach meinem Verständnis von Minecraft Vanilla) bei amplifier: 127 den Wert 255 erhalten
Amplifier 0 = Trank Level 1, Amplifier 1 = Trank Level 2, Amplifier 2 = Trank Level 3, Amplifier 3 = Trank Level 4, usw. Zumindest nach meinem Verständnis...

**Comment by CombatTiger** [comment]
@sebastianbinder Aber dann wäre das was ich gerne hätte nicht möglich oder verstehe ich das falsch? Weisst du ob die Definition von aplifier und die Umsetzung in Minecraft Spigot/Java abhängig ist oder amplifier im Plugin selbst definiert wird?

**Comment by sebastianbinder** [comment]
@CombatTiger Was passiert denn, wenn du den Amplifier auf 254 oder 255 setzt?

**Comment by CombatTiger** [comment]
@sebastianbinder Dann wird der Trank als Wasserflasche angezeigt, es entsteht also ein Fehler. Durch Ausprobieren bin ich dann auf den Maximalwert 127 gekommen.

**Comment by sebastianbinder** [comment]
@CombatTiger Kommt dann ein Fehler im Logfile?

**Comment by CombatTiger** [comment]
@sebastianbinder Zunächst einmal muss ich mich korrigieren, er zeigt den Trank sehr wohl korrket an, man kann ihn jedoch nicht kaufen. Sowohl Konsole als auch Logfile enthalten keine Fehlermeldungen o. ä.

**Comment by sebastianbinder** [comment]
Inwiefern kann man ihn "nicht kaufen"? Was passiert?

**Comment by CombatTiger** [comment]
@sebastianbinder Naja, man klickt auf den Trank, doch es passiert einfach nichts. Das Icon des Trankes bewegt sich zwar, wie es es eben macht, wenn man etwas kauft, doch diese Bewegung entsteht auch, wenn man nicht genug Ressourcen hat.

**Comment by sebastianbinder** [comment]
Also. Ich habe mal ein bisschen recherchiert und getestet:
> Internally, and in the /effect command and potion Amplifier NBT tags, the game stores an "amplifier" value rather than the level. The amplifier is one less than the level, for example Strength II has an amplifier of 1.
Due to the way this amplifier is stored in NBT, amplifiers of 128 to 255 (levels 129 to 256) in NBT tags (e.g. on potions) are treated as if they were −128 to −1 (levels −127 to 0) respectively. The /effect command initially applies such amplifiers in their positive-valued sense but this is later converted to the negative-valued interpretation, leading to inconsistent results.
(Quelle: http://minecraft.gamepedia.com/Status_effect)

**Daraus resultiert:**
`/give <PLAYER> potion 1 8203 {CustomPotionEffects:[{Id:8,Amplifier:256,Duration:10000}]}`
entspräche in der `shop.yml`
```yml
    - reward:
      - type: POTION
        damage: 8203
        meta:
          ==: ItemMeta
          meta-type: POTION
          custom-effects:
          - ==: PotionEffect
            effect: 8
            duration: 10000
            amplifier: -1
            ambient: false
            has-particles: false
```

`/give <PLAYER> potion 1 8203 {CustomPotionEffects:[{Id:8,Amplifier:255,Duration:10000}]}`
entspräche in der `shop.yml`
```yml
    - reward:
      - type: POTION
        damage: 8203
        meta:
          ==: ItemMeta
          meta-type: POTION
          custom-effects:
          - ==: PotionEffect
            effect: 8
            duration: 10000
            amplifier: -2
            ambient: false
            has-particles: false
```
usw.

Ich hoffe, ich konnte dir damit weiterhelfen. Bitte um Feedback.
