### ISSUE TITLE
[GER] Meta oder Sub ID?

### ISSUE THREAD

**Issue by DampfWaffel** [BedwarsRel/BedwarsRel#793]
Guten Tag,

ich wollte in BedWars Shop folgendes tauschen, Braun gefärbter Ton(159:12) gegen ein Stein Schwert, aber leider bekomme ich es nicht hin und meta funktioniert nur in der Config und nicht bei der shop.yml oder mache ich da irgendwas falsch?

```
shop:
  armor:
    item: DIAMOND_CHESTPLATE
    name: Armour
    order: 10
    permission: bw.base
    lore:
    - Protect yourself with armor! Click here.
    offers:
    - price:
      - type: SUGAR
      reward:
      - type: LEATHER_HELMET
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - reward:
      - type: DIAMOND_SWORD
        amount: 1
      price:
      - type: STAINED_CLAY
        meta: 12
        amount: 2
schema-version: 1
```

`Couldn't parse item in category "Armour": {reward=[{type=DIAMOND_SWORD, amount=1}], price=[{type=STAINED_CLAY:12, amount=2}]}`

Server Infos:
 - Version: MC: 1.8.8 - 1.8.8-R0.1-SNAPSHOT
 - Neuste BedWars Version

Könnte mir irgendjemand Helfen?
Vielen Dank.
