### ISSUE TITLE
NullPointerException when loading ResourceSpawners from game config

### ISSUE THREAD

**Issue by MPK1** [BedwarsRel/BedwarsRel#816]
Hi there,

i have a very heavy issue:

Every time i reload/restart my server, i get a lot of NullPointerExeptions, one for every ResourceSpawner in my game. They happen while deserialising ResourceSpawners from the config. Because of the error "Could not call constructor 'public io.github.bedwarsrel.game.ResourceSpawner(java.util.Map)' of class io.github.bedwarsrel.game.ResourceSpawner for deserialization" and the fact that i am actually java developer I think that the line 38 "String name = deserialize.get("name").toString();" tries to invoke toString(); on null. I don't know why the Resource names are always replaced with null...

To give you a quick overview, I reconstruct the whole progress:
1. I create a game, everything normal. I play the game, everythink working.
2. I look in the game.yml, everything normal. The serialized ResourceSpawners have name: bronze or name: iron...
3. I reload/restart the server. I get a NullPointerExeption for every ResourceSpawner it tries to deserialize.
4. I look in the config and AT ALL RESOURCESPAWNERS THE NAME ATTRIBUTE IS SET TO NULL

When is this happening and why?

I uploaded one of the StackTraces here: https://pastebin.com/57ijr1Gm

**Comment by sebastianbinder** [comment]
please send output of `/bw debugpaste`

**Comment by MPK1** [comment]
https://hastebin.com/quyuqiqehu

**Comment by sebastianbinder** [comment]
According to your resource spawner config
```yml
resource:
  bronze:
    item:
    - type: CLAY_BRICK
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §4Bronze
    spawn-interval: 1000
    spread: 1.0
  iron:
    item:
    - type: IRON_INGOT
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §7Iron
    spawn-interval: 10000
    spread: 1.0
  gold:
    item:
    - type: GOLD_INGOT
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §6Gold
    spawn-interval: 20000
    spread: 1.0
```
there is no name set. This is fine.

So `String name = deserialize.get("name").toString();` should never be called, as there is a `if (deserialize.containsKey("name")) {` in the line before. According to the fact that you are actually a java developer I think you could have seen this...

>> I look in the config and AT ALL RESOURCESPAWNERS THE NAME ATTRIBUTE IS SET TO NULL
The name attribute is not needed - so just remove it and everything should be fine :)

**Comment by MPK1** [comment]
We're talking about sth different:

You copied the resource section, I'm talking about ResourceSpawners



```
spawner:
- ==: RessourceSpawner
  name: null
  location:
    world: aztec
    x: 489.5
    y: 150.0
    z: 923.5
    pitch: 90.0
    yaw: 90.0
- ==: RessourceSpawner
  name: null
  location:
    world: aztec
    x: 489.5
    y: 150.0
    z: 915.5
    pitch: 90.0
    yaw: 90.0
```
