### ISSUE TITLE
shop.yml can't be loaded properly

### ISSUE THREAD

**Issue by Soldier233** [BedwarsRel/BedwarsRel#836]
I am running the latest release of your plugin on the up-to-date Spigot 1.8.8
And I found that the plugin can't load shop.yml correctly
the potions can't display or apply its effect in the default copy of shop.yml
I hope you can fix it soon!

**Comment by Soldier233** [comment]
Compared to V1.2.8(the version I used to use)
It seemed that the color code '&' has been disabled in shop.yml?
Or I need to use '§' to replace them?

**Comment by sebastianbinder** [comment]
for me color codes like
```yml
    - reward:
      - type: STRING
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: "§fTrap"
```
work perfectly.

regarding the potions: without any proper details on your setup, I cannot help you here.
