### ISSUE TITLE
Tnt sheep is crashing the shop what is wrong.

### ISSUE THREAD

**Issue by ImStanga** [BedwarsRel/BedwarsRel#862]
- reward:
      - type: MONSTER_EGG
        damage: 91
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: "TNT-Sau
          lore:
          - "Du vil ikke vite hva denne gjør"
          internal: H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWANzkhNLWBgAAABt1TGHQAAAA==
      price:
      - type: CLAY_BRICK
        amount: 64

**Comment by flixoflax** [comment]
Should not crash the Shop like this:

`    - reward:
      - type: MONSTER_EGG
        amount: 1
        damage: 91
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: TNT-Sheep
          damage: 91
          lore:
          - Benutze das TNT-Schaf! Es wird
          - zu deinem nächsten Gegner laufen
          - und innerhalb von 8 Sekunden explodieren!
          internal: H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWANzkhNLWBgAAABt1TGHQAAAA==
      price:
      - type: CLAY_BRICK
        amount: 64`

**Comment by flixoflax** [comment]
Sorry Problems while copying The Code its damage in the meta section

**Comment by flixoflax** [comment]
And you actualy forgot the " next to TNT-Sau

**Comment by flixoflax** [comment]
Again make a " next to Tnt-Sau.  thats it. no damage in the meta section...

**Comment by sebastianbinder** [comment]
```yml
- reward:
  - type: MONSTER_EGG
    damage: 91
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: "TNT-Sau"
      lore:
      - "Du vil ikke vite hva denne gjør"
      internal: H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWANzkhNLWBgAAABt1TGHQAAAA==
  price:
  - type: CLAY_BRICK
    amount: 64
```
