### ISSUE TITLE
Experience Bug

### ISSUE THREAD

**Issue by Sukram28** [BedwarsRel/BedwarsRel#863]
There is a huge Bug with this Plugin!
Ist is it possible to fix this:
If a Player looses a game than the player don't get there Experience back ..
The Experience will only be resetted on the winner team.

**Comment by flixoflax** [comment]
Dont understand

**Comment by sebastianbinder** [comment]
Interesting. There is a method which handles this and there is no difference between the teams. I might have a closer look on that, but because of lack of time this will take a while.

**Comment by Sukram28** [comment]
Ok thank you :)
Here are my config settings
(only things that I changed from the normal generated config)

```
die-on-void: true
endgame:
  mainlobby-enabled: true
  all-players-to-mainlobby: true
```
