### ISSUE TITLE
Shop GUI reflects only gold as cost instead of custom item, like diamond.

### ISSUE THREAD

**Issue by Capri205** [BedwarsRel/BedwarsRel#879]
Hi. Might be a bug, but could be our config. When we add diamond spawners into the game and change the shop items to require diamonds, they do actually require the diamond amount specified to purchase, but the shop GUI always shows "gold" instead of diamond. For example, an item is set to cost the following in the shop.yml:

- type: GOLD_INGOT
amount: 10
- type: DIAMOND
amount: 2

and you can only buy it with that but the shop GUI when you hover the mouse over the item shows:

10 gold
2 gold

Let me know if you can fix that as it's not obvious to players what things really cost :)

Otherwise, awsome plugin!

**Comment by sebastianbinder** [comment]
Could you please provide the „/bw debugpaste“ output?

**Comment by Capri205** [comment]
Here you go: https://hastebin.com/payecipumo

**Comment by sebastianbinder** [comment]
Your "diamond" resource has a display-name "gold"…
```yml
  diamond:
    item:
    - type: DIAMOND
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §6Gold
    spawn-interval: 40000
    spread: 1.0
```
Might be a good idea to change that one to diamond...
